import adwaita_lustre_dev/icons.{type Icon}
import gleam/dict
import gleam/int
import gleam/list
import gleam/option.{None, Some}
import gleam/string
import simplifile

const output_path = "./src/adwaita_lustre.gleam"

const reserved_words = [
  "as", "assert", "auto", "case", "const", "delegate", "derive", "echo", "else",
  "fn", "if", "implement", "import", "let", "macro", "opaque", "panic", "pub",
  "test", "todo", "type", "use",
]

const signature_tail = "(attributes: List(Attribute(message))) -> Element(message) {"

const header = "//// This file is generated by `dev/adwaita_lustre_dev.gleam`, do not edit it.
////
//// The icons come from [adwaita-icon-theme](https://gitlab.gnome.org/GNOME/adwaita-icon-theme)
//// by the [GNOME Project](https://www.gnome.org), licensed under LGPL-3.0 or
//// CC-BY-SA-3.0 (see the `LICENSE` file). The SVG files have been modified:
//// they are minified and stripped of editor metadata.

import lustre/attribute.{type Attribute}
import lustre/element.{type Element}

"

pub fn generate(icons: List(Icon)) -> Int {
  let occurrences =
    list.fold(icons, dict.new(), fn(counts, icon) {
      dict.upsert(counts, icon.name, fn(count) {
        case count {
          Some(count) -> count + 1
          None -> 1
        }
      })
    })
  let source =
    header
    <> {
      icons
      |> list.map(fn(icon) { render_function(icon, occurrences) })
      |> string.join("\n")
    }
  let assert Ok(Nil) = simplifile.write(output_path, source)
  list.length(icons)
}

fn render_function(icon: Icon, occurrences: dict.Dict(String, Int)) -> String {
  let is_duplicated = case dict.get(occurrences, icon.name) {
    Ok(count) -> count > 1
    Error(Nil) -> False
  }
  let name = case is_duplicated {
    True -> icon.directory <> "_" <> icon.name
    False -> icon.name
  }
  let attributes =
    render_attributes(list.map(icon.attributes, render_attribute))
  let signature = "pub fn " <> function_name(name) <> signature_tail
  let signature = case string.length(signature) > 80 {
    True ->
      "pub fn "
      <> function_name(name)
      <> "(\n  attributes: List(Attribute(message)),\n) -> Element(message) {"
    False -> signature
  }
  signature
  <> "\n  element.unsafe_raw_html(\n    \"http://www.w3.org/2000/svg\",\n    \"svg\",\n"
  <> attributes
  <> "\n    "
  <> string.inspect(icon.inner_html)
  <> ",\n  )\n}\n"
}

fn render_attributes(attributes: List(String)) -> String {
  let one_line = "    [" <> string.join(attributes, ", ") <> ", ..attributes],"
  case string.length(one_line) > 81 {
    False -> one_line
    True ->
      "    [\n"
      <> string.join(
        list.map(attributes, fn(item) { "      " <> item <> "," }),
        "\n",
      )
      <> "\n      ..attributes\n    ],"
  }
}

fn render_attribute(attribute: #(String, String)) -> String {
  case attribute.0, int.parse(attribute.1) {
    "width", Ok(_) | "height", Ok(_) ->
      "attribute." <> attribute.0 <> "(" <> attribute.1 <> ")"
    _, _ ->
      "attribute.attribute("
      <> string.inspect(attribute.0)
      <> ", "
      <> string.inspect(attribute.1)
      <> ")"
  }
}

fn function_name(name: String) -> String {
  let identifier =
    name
    |> string.lowercase
    |> string.to_graphemes
    |> list.map(fn(character) {
      case is_identifier_character(character) {
        True -> character
        False -> "_"
      }
    })
    |> string.concat
  let identifier = case string.first(identifier) {
    Ok("0")
    | Ok("1")
    | Ok("2")
    | Ok("3")
    | Ok("4")
    | Ok("5")
    | Ok("6")
    | Ok("7")
    | Ok("8")
    | Ok("9") -> "icon_" <> identifier
    _ -> identifier
  }
  case list.contains(reserved_words, identifier) {
    True -> identifier <> "_"
    False -> identifier
  }
}

fn is_identifier_character(character: String) -> Bool {
  string.contains("abcdefghijklmnopqrstuvwxyz0123456789_", character)
}
